from __future__ import annotations

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from catalog_service import build_active_generic_groups, deactivate_missing_offers_for_chain, upsert_catalog_products
from models import CatalogRefreshRun, CanonicalProduct


def _demo_product(
    *,
    chain: str,
    store_id: str,
    store_name: str,
    product_id: str,
    name: str,
    brand: str,
    barcode: str,
    price: float,
    regular_price: float,
    sale_price: float | None = None,
    discount_percent: float | None = None,
    deal: dict | None = None,
    unit_description: str,
    unit_of_measure: str,
    unit_qty: float,
    unit_qty_si: float,
    unit_dimension: str,
    price_per_base_unit: float,
    is_weighable: bool = False,
    image_url: str | None = None,
) -> dict:
    return {
        "chain": chain,
        "store_id": store_id,
        "store_name": store_name,
        "product_id": product_id,
        "name": name,
        "brand": brand,
        "manufacturer": brand,
        "barcode": barcode,
        "price": price,
        "regular_price": regular_price,
        "sale_price": sale_price,
        "discount_percent": discount_percent,
        "deal": deal,
        "unit_description": unit_description,
        "unit_of_measure": unit_of_measure,
        "unit_qty": unit_qty,
        "unit_qty_si": unit_qty_si,
        "unit_dimension": unit_dimension,
        "price_per_base_unit": price_per_base_unit,
        "is_weighable": is_weighable,
        "image_url": image_url,
        "category_ids": ["demo"],
        "scraped_at": "2026-05-02T12:00:00+00:00",
    }


DEMO_PRODUCTS: list[dict] = [
    _demo_product(
        chain="carrefour",
        store_id="3003",
        store_name="קרפור כפר סבא",
        product_id="cf-milk-tnuva-3003",
        name="חלב תנובה 3% 1 ליטר",
        brand="תנובה",
        barcode="7290000066882",
        price=6.00,
        regular_price=6.50,
        sale_price=6.00,
        discount_percent=8.0,
        deal={
            "has_deal": True,
            "deal_type": "price_reduction",
            "deal_description": "מבצע שבועי",
            "deal_price": 6.0,
            "deal_price_per_unit": 6.0,
        },
        unit_description="1 ליטר",
        unit_of_measure='מ"ל',
        unit_qty=1000,
        unit_qty_si=1000,
        unit_dimension="volume",
        price_per_base_unit=0.60,
        image_url="https://images.example.com/milk-tnuva.jpg",
    ),
    _demo_product(
        chain="carrefour",
        store_id="3014",
        store_name="קרפור תל אביב",
        product_id="cf-milk-tnuva-3014",
        name="חלב תנובה 3% 1 ליטר",
        brand="תנובה",
        barcode="7290000066882",
        price=5.50,
        regular_price=6.20,
        sale_price=5.50,
        discount_percent=11.3,
        deal={
            "has_deal": True,
            "deal_type": "price_reduction",
            "deal_description": 'חיסכון לסופ"ש',
            "deal_price": 5.5,
            "deal_price_per_unit": 5.5,
        },
        unit_description="1 ליטר",
        unit_of_measure='מ"ל',
        unit_qty=1000,
        unit_qty_si=1000,
        unit_dimension="volume",
        price_per_base_unit=0.55,
        image_url="https://images.example.com/milk-tnuva.jpg",
    ),
    _demo_product(
        chain="ramilevi",
        store_id="1332",
        store_name="רמי לוי מודיעין",
        product_id="rl-milk-tnuva-1332",
        name="חלב תנובה 3% 1 ליטר",
        brand="תנובה",
        barcode="7290000066882",
        price=5.80,
        regular_price=6.10,
        sale_price=5.80,
        discount_percent=4.9,
        deal={
            "has_deal": True,
            "deal_type": "price_reduction",
            "deal_description": "מבצע מועדון",
            "deal_price": 5.8,
            "deal_price_per_unit": 5.8,
        },
        unit_description="1 ליטר",
        unit_of_measure='מ"ל',
        unit_qty=1000,
        unit_qty_si=1000,
        unit_dimension="volume",
        price_per_base_unit=0.58,
        image_url="https://images.example.com/milk-tnuva.jpg",
    ),
    _demo_product(
        chain="shufersal",
        store_id="global",
        store_name="שופרסל אונליין",
        product_id="sh-milk-tnuva",
        name="חלב תנובה 3% 1 ליטר",
        brand="תנובה",
        barcode="7290000066882",
        price=5.90,
        regular_price=5.90,
        unit_description="1 ליטר",
        unit_of_measure='מ"ל',
        unit_qty=1000,
        unit_qty_si=1000,
        unit_dimension="volume",
        price_per_base_unit=0.59,
        image_url="https://images.example.com/milk-tnuva.jpg",
    ),
    _demo_product(
        chain="carrefour",
        store_id="3003",
        store_name="קרפור כפר סבא",
        product_id="cf-milk-tara-3003",
        name="חלב טרה 3% 1 ליטר",
        brand="טרה",
        barcode="7290111111111",
        price=5.30,
        regular_price=5.60,
        sale_price=5.30,
        discount_percent=5.4,
        deal={
            "has_deal": True,
            "deal_type": "price_reduction",
            "deal_description": "מחיר מיוחד",
            "deal_price": 5.3,
            "deal_price_per_unit": 5.3,
        },
        unit_description="1 ליטר",
        unit_of_measure='מ"ל',
        unit_qty=1000,
        unit_qty_si=1000,
        unit_dimension="volume",
        price_per_base_unit=0.53,
        image_url="https://images.example.com/milk-tara.jpg",
    ),
    _demo_product(
        chain="ramilevi",
        store_id="1332",
        store_name="רמי לוי מודיעין",
        product_id="rl-milk-tara-1332",
        name="חלב טרה 3% 1 ליטר",
        brand="טרה",
        barcode="7290111111111",
        price=5.40,
        regular_price=5.40,
        unit_description="1 ליטר",
        unit_of_measure='מ"ל',
        unit_qty=1000,
        unit_qty_si=1000,
        unit_dimension="volume",
        price_per_base_unit=0.54,
        image_url="https://images.example.com/milk-tara.jpg",
    ),
    _demo_product(
        chain="carrefour",
        store_id="3003",
        store_name="קרפור כפר סבא",
        product_id="cf-eggs-3003",
        name="ביצים M 12 יחידות",
        brand="גליקסמן",
        barcode="7290222222222",
        price=14.00,
        regular_price=14.00,
        unit_description="12 יחידות",
        unit_of_measure="יח'",
        unit_qty=12,
        unit_qty_si=12,
        unit_dimension="count",
        price_per_base_unit=1.1667,
        image_url="https://images.example.com/eggs.jpg",
    ),
    _demo_product(
        chain="carrefour",
        store_id="3014",
        store_name="קרפור תל אביב",
        product_id="cf-eggs-3014",
        name="ביצים M 12 יחידות",
        brand="גליקסמן",
        barcode="7290222222222",
        price=16.00,
        regular_price=16.00,
        unit_description="12 יחידות",
        unit_of_measure="יח'",
        unit_qty=12,
        unit_qty_si=12,
        unit_dimension="count",
        price_per_base_unit=1.3333,
        image_url="https://images.example.com/eggs.jpg",
    ),
    _demo_product(
        chain="ramilevi",
        store_id="1332",
        store_name="רמי לוי מודיעין",
        product_id="rl-eggs-1332",
        name="ביצים M 12 יחידות",
        brand="גליקסמן",
        barcode="7290222222222",
        price=13.50,
        regular_price=13.50,
        unit_description="12 יחידות",
        unit_of_measure="יח'",
        unit_qty=12,
        unit_qty_si=12,
        unit_dimension="count",
        price_per_base_unit=1.1250,
        image_url="https://images.example.com/eggs.jpg",
    ),
    _demo_product(
        chain="shufersal",
        store_id="global",
        store_name="שופרסל אונליין",
        product_id="sh-eggs",
        name="ביצים M 12 יחידות",
        brand="גליקסמן",
        barcode="7290222222222",
        price=13.90,
        regular_price=15.20,
        sale_price=13.90,
        discount_percent=8.6,
        deal={
            "has_deal": True,
            "deal_type": "price_reduction",
            "deal_description": "מחיר רשת",
            "deal_price": 13.9,
            "deal_price_per_unit": 13.9,
        },
        unit_description="12 יחידות",
        unit_of_measure="יח'",
        unit_qty=12,
        unit_qty_si=12,
        unit_dimension="count",
        price_per_base_unit=1.1583,
        image_url="https://images.example.com/eggs.jpg",
    ),
    _demo_product(
        chain="carrefour",
        store_id="3003",
        store_name="קרפור כפר סבא",
        product_id="cf-cottage-3003",
        name="קוטג׳ תנובה 250 גרם",
        brand="תנובה",
        barcode="7290333333333",
        price=6.20,
        regular_price=6.20,
        deal={
            "has_deal": True,
            "deal_type": "multi_buy",
            "deal_description": "2 ב-10",
            "deal_price": 10.0,
            "deal_min_qty": 2,
            "deal_price_per_unit": 5.0,
            "price_per_base_unit": 2.48,
            "price_per_base_unit_deal": 2.0,
        },
        unit_description="250 גרם",
        unit_of_measure="גרם",
        unit_qty=250,
        unit_qty_si=250,
        unit_dimension="mass",
        price_per_base_unit=2.48,
        image_url="https://images.example.com/cottage.jpg",
    ),
    _demo_product(
        chain="ramilevi",
        store_id="1332",
        store_name="רמי לוי מודיעין",
        product_id="rl-cottage-1332",
        name="קוטג׳ תנובה 250 גרם",
        brand="תנובה",
        barcode="7290333333333",
        price=5.50,
        regular_price=6.20,
        sale_price=5.50,
        discount_percent=11.3,
        deal={
            "has_deal": True,
            "deal_type": "price_reduction",
            "deal_description": "הנחת סניף",
            "deal_price": 5.5,
            "deal_price_per_unit": 5.5,
        },
        unit_description="250 גרם",
        unit_of_measure="גרם",
        unit_qty=250,
        unit_qty_si=250,
        unit_dimension="mass",
        price_per_base_unit=2.20,
        image_url="https://images.example.com/cottage.jpg",
    ),
    _demo_product(
        chain="carrefour",
        store_id="3003",
        store_name="קרפור כפר סבא",
        product_id="cf-chicken-3003",
        name='חזה עוף טרי ארוז 1 ק"ג',
        brand="עוף טוב",
        barcode="7290444444444",
        price=36.00,
        regular_price=38.00,
        sale_price=36.00,
        discount_percent=5.3,
        deal={
            "has_deal": True,
            "deal_type": "price_reduction",
            "deal_description": "מבצע בשרי",
            "deal_price": 36.0,
            "deal_price_per_unit": 36.0,
        },
        unit_description='1 ק"ג',
        unit_of_measure='ק"ג',
        unit_qty=1,
        unit_qty_si=1000,
        unit_dimension="mass",
        price_per_base_unit=36.0,
        is_weighable=True,
        image_url="https://images.example.com/chicken.jpg",
    ),
    _demo_product(
        chain="ramilevi",
        store_id="1332",
        store_name="רמי לוי מודיעין",
        product_id="rl-chicken-1332",
        name='חזה עוף טרי ארוז 1 ק"ג',
        brand="עוף טוב",
        barcode="7290444444444",
        price=34.50,
        regular_price=34.50,
        unit_description='1 ק"ג',
        unit_of_measure='ק"ג',
        unit_qty=1,
        unit_qty_si=1000,
        unit_dimension="mass",
        price_per_base_unit=34.5,
        is_weighable=True,
        image_url="https://images.example.com/chicken.jpg",
    ),
]


async def seed_demo_catalog(session: AsyncSession) -> None:
    existing = (
        await session.execute(select(func.count(CanonicalProduct.id)))
    ).scalar_one_or_none()
    if existing:
        return

    run = CatalogRefreshRun(
        source="seed",
        status="running",
        chains_scraped=sorted({product["chain"] for product in DEMO_PRODUCTS}),
        chains_failed=[],
        products_upserted=0,
        errors=[],
    )
    session.add(run)
    await session.flush()
    products_upserted = await upsert_catalog_products(session, DEMO_PRODUCTS, run.id)
    for chain in sorted({product["chain"] for product in DEMO_PRODUCTS}):
        store_ids = {product["store_id"] for product in DEMO_PRODUCTS if product["chain"] == chain}
        await deactivate_missing_offers_for_chain(session, chain, run.id, store_ids)
    await build_active_generic_groups(session)
    run.status = "done"
    run.products_upserted = products_upserted
    run.finished_at = run.started_at
